# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'GOOGLE', b'Google'), (b'FACEBOOK', b'Facebook'), (b'MICROSOFT', b'Microsoft')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'MIN_STEPS_IN_INFINITE_GRIDBOOKMARK', b'Min Steps in Infinite Grid')], max_length=255)),
                ('category', models.CharField(choices=[(b'ARRAY', b'Array'), (b'LINKED_LIST', b'Linked List')], max_length=255)),
                ('difficulty', models.CharField(choices=[(b'EASY', b'Easy'), (b'MEDIUM', b'Medium'), (b'HARD', b'Hard')], max_length=255)),
                ('companies', models.ManyToManyField(related_name='problems', to='backend.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'C_PLUS_PLUS', b'C++'), (b'JAVA', b'Java'), (b'PYTHON', b'Python'), (b'JAVASCRIPT', b'Javascript')], max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.Candidate')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='backend.Problem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('problem', 'candidate')]),
        ),
    ]
