# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'1', b'C++'), (b'10', b'Java'), (b'4', b'Python'), (b'35', b'Javascript')], max_length=255)),
                ('sourceCode', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='backend.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[(b'ARRAY', b'Array'), (b'LINKED_LIST', b'Linked List')], max_length=255)),
                ('difficulty', models.CharField(choices=[(b'EASY', b'Easy'), (b'MEDIUM', b'Medium'), (b'HARD', b'Hard')], max_length=255)),
                ('companies', models.ManyToManyField(related_name='problems', to='backend.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'1', b'C++'), (b'10', b'Java'), (b'4', b'Python'), (b'35', b'Javascript')], max_length=255)),
                ('headers', models.TextField()),
                ('userSkeleton', models.TextField()),
                ('runnerFunction', models.TextField()),
                ('cPlusHeaders', models.TextField()),
                ('cPlusUserSkeleton', models.TextField()),
                ('cPlusRunnerFunction', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemFunctions', to='backend.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'1', b'C++'), (b'10', b'Java'), (b'4', b'Python'), (b'35', b'Javascript')], max_length=255)),
                ('source', models.TextField(verbose_name=b'source code')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.Candidate')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='backend.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'-1', b'Awaiting Compilation'), (b'0', b'Done'), (b'1', b'Compiling'), (b'3', b'Running')], max_length=255)),
                ('submissionDetail', models.TextField(verbose_name=b'')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='backend.Submission')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCaseSubmissions', to='backend.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='backend.Problem'),
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('problem', 'candidate')]),
        ),
    ]
