# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[(b'ARRAY', b'Array'), (b'LINKED_LIST', b'Linked List'), (b'MATH', b'Math')], max_length=255),
        ),
    ]
