# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='isSample',
            field=models.BooleanField(default=False, verbose_name=b'Compile and run sample tests or not'),
        ),
    ]
