# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceCode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cHeaders', models.TextField()),
                ('cUserSkeleton', models.TextField()),
                ('cRunnerFunction', models.TextField()),
                ('cPlusHeaders', models.TextField()),
                ('cPlusUserSkeleton', models.TextField()),
                ('cPlusRunnerFunction', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='college',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='problemfunctions',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemFunctions', to='backend.Problem'),
        ),
        migrations.AddField(
            model_name='draft',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='backend.Candidate'),
        ),
        migrations.AddField(
            model_name='draft',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='backend.Problem'),
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('problem', 'candidate')]),
        ),
    ]
