# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_submission_issample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasesubmission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='testcasesubmission',
            name='testCase',
        ),
        migrations.DeleteModel(
            name='TestCaseSubmission',
        ),
    ]
