# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160329_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='backend.Company'),
        ),
        migrations.AddField(
            model_name='submission',
            name='compilerLog',
            field=models.TextField(default=None, null=True, verbose_name=b'Compiler log lines modified by our util function'),
        ),
        migrations.AddField(
            model_name='submission',
            name='originalCompilerLog',
            field=models.TextField(default=None, null=True, verbose_name=b'Compiler log returned from hacker earth api'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[(b'PENDING', b'Pending'), (b'CE', b'Compilation Error'), (b'AC', b'Correct Answer'), (b'WA', b'Wrong Answer'), (b'TLE', b'Time Limit Exceeded'), (b'MLE', b'Memory Limit Exceeded'), (b'OTHER', b'Reason Not Yet found')], default=b'PENDING', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='backend.College'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='language',
            field=models.CharField(choices=[(b'C', b'C'), (b'C++', b'C++'), (b'JAVA', b'Java'), (b'PYTHON', b'Python'), (b'JAVASCRIPT', b'Javascript')], max_length=255),
        ),
        migrations.AlterField(
            model_name='problemfunction',
            name='language',
            field=models.CharField(choices=[(b'C', b'C'), (b'C++', b'C++'), (b'JAVA', b'Java'), (b'PYTHON', b'Python'), (b'JAVASCRIPT', b'Javascript')], max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[(b'C', b'C'), (b'C++', b'C++'), (b'JAVA', b'Java'), (b'PYTHON', b'Python'), (b'JAVASCRIPT', b'Javascript')], max_length=255),
        ),
    ]
