# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160329_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memoryUsed',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name=b'Memory used by the program in kilo bytes'),
        ),
        migrations.AddField(
            model_name='submission',
            name='timeUsed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, null=True, verbose_name=b'Time taken by the program'),
        ),
    ]
