# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20160329_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='failedCase',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name=b'Test Case # failed because of wrong answer'),
        ),
    ]
