# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160329_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemfunction',
            old_name='runnerFunction',
            new_name='footer',
        ),
        migrations.RenameField(
            model_name='problemfunction',
            old_name='userSkeleton',
            new_name='skeleton',
        ),
    ]
