# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20160329_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memoryLimit',
            field=models.PositiveIntegerField(default=262144, verbose_name=b'Memory limit in KB'),
        ),
        migrations.AddField(
            model_name='problem',
            name='timeLimit',
            field=models.PositiveIntegerField(default=1, verbose_name=b'TimeLimit'),
        ),
    ]
