# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20160329_0845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemfunction',
            unique_together=set([('problem', 'language')]),
        ),
    ]
