# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20160330_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
