# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='title',
        ),
    ]
