# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20160330_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='compilerLog',
            new_name='compilerErrorLog',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='originalCompilerLog',
            new_name='originalCompilerErrorLog',
        ),
    ]
