# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20160401_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[(b'QE', b'Queued'), (b'CE', b'Compilation Error'), (b'AC', b'Correct Answer'), (b'WA', b'Wrong Answer'), (b'TLE', b'Time Limit Exceeded'), (b'MLE', b'Memory Limit Exceeded'), (b'OTHER', b'Reason Not Yet found')], default=b'QE', max_length=255, null=True),
        ),
    ]
